# Generated by Django 3.2.3 on 2021-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='section',
            field=models.IntegerField(choices=[(0, 'Matemática'), (1, 'Algoritmos')], default=0),
        ),
    ]
